### ISSUE TITLE
Bug Noeud non créé

### ISSUE THREAD

**Issue by YohanTremblay** [ChuckD46/STIMULUS_V2#100]
# Description

Lorsque tu créés le graphe, un premier noeud de STRUCTURE sera créé automatiquement, mais si c'est long et il y a des espaces, le noeud ne se créé pas,

## Reproduire le BUG

1. Créer un graph
2. Nommer le graph : _Je test le bug Lol_
3. Observer le bug

**Comment by Marc-Antoine-B** [comment]
réglé dans #110
