### ISSUE TITLE
Suppression Graph pas mise à jour sur menu

### ISSUE THREAD

**Issue by YohanTremblay** [ChuckD46/STIMULUS_V2#103]
# Description 

Lors de la suppression et aussi lors de l'ajout la menu de gauche ne se fait pas mettre à jour :

![image](https://github.com/ChuckD46/STIMULUS_V2/assets/89463262/30432596-c147-4aeb-93c6-6cb5801173ec)

## Reproduire le bug

1. Créer un graph
2. Observer le bug

1. Supprimer un graph
2. Observer le bug

**Comment by Marc-Antoine-B** [comment]
Update navbar statehaschanged
delete page avec composant dans graph

**Comment by Marc-Antoine-B** [comment]
Patch en pull request #110
