### ISSUE TITLE
Set default node radius to 40

### ISSUE THREAD

**Issue by LouisSeranne** [ChuckD46/STIMULUS_V2#112]
The default node radius when creating a new node is 0
It would be nice to set the default to a valid value (e.g. 40)

**Comment by YohanTremblay** [comment]
L'alerte de la valeur qui n'est pas bonne devrait pas être :
_La valeur doit être supérieur à 40_

Mais elle devrait être :
_La valeur doit être supérieur à 40 et inférieur à 80_

**Comment by corentinurlacher** [comment]
PATCH

**Comment by LouisSeranne** [comment]
Fixed with #134
