### ISSUE TITLE
Dépendances ne sont pas claires

### ISSUE THREAD

**Issue by DarOli2131947** [ChuckD46/STIMULUS_V2#121]
Un graphe requiert un groupe, un groupe requiert un cour et un cour peut être créé seul. L'application n'explique pas ceci et pourrait causer une confusion lors de la création d'un graphe.

Une page d'aide, une petite note quelque part ou même une petite documentation quelque part arrangerait ce problème.

**Comment by Marc-Antoine-B** [comment]
En cours.

**Comment by Marc-Antoine-B** [comment]
Ça a toujours été comme ça même dans l'ancien projet. Juste au lieu de faire un insert y'a des beaux petits form
