### ISSUE TITLE
"Liste des étudiants à ajouter" devrait être une barre de recherche

### ISSUE THREAD

**Issue by DarOli2131947** [ChuckD46/STIMULUS_V2#122]
Présentement, la liste est composée de points à cocher. Ceci ne marcheras pas avec des milliers d'étudiants puisque trouver l'étudiant spécifique que le professeur veut ajouter se démontrera difficile (surtout si les élève sont nommé par code DA).

Un exemple rapide à quoi ce scénario pourrait ressembler (le css n'est pas parfait, mais il démontre ce que je veut dire) :
![image](https://github.com/ChuckD46/STIMULUS_V2/assets/89397446/9ca6cc8b-4b83-4308-8b20-4a9137a228cd)

**Comment by Marc-Antoine-B** [comment]
Sera réglé avec le travail de Charles.
