### ISSUE TITLE
"Une erreur non gérée s'est produite"

### ISSUE THREAD

**Issue by DarOli2131947** [ChuckD46/STIMULUS_V2#127]
Lorsque l'on navigue dans l'application, il y a une chance de tomber sur une erreur : 

![image](https://github.com/ChuckD46/STIMULUS_V2/assets/89397446/1196d9ac-7342-4fc7-bac2-2a4342c83500)

Rafraichir la page fait disparaitre l'erreur

(plus d'information sur ce bug à venir)

**Comment by Marc-Antoine-B** [comment]
ça devrait être patch dans dev, j'ai mit un try catch
