### ISSUE TITLE
Page active n'est pas surlignée

### ISSUE THREAD

**Issue by DarOli2131947** [ChuckD46/STIMULUS_V2#131]
Lorsque l'utilisateur est sur une page, celle si devient rouge dans la barre de navigation comme ceci :

![image](https://github.com/ChuckD46/STIMULUS_V2/assets/89397446/3203c82c-3a71-47c6-8bc9-12cf54401ac8)

Mais cela n'arrive pas si l'utilisateur est sur une page comme celle d'un groupe :

![image](https://github.com/ChuckD46/STIMULUS_V2/assets/89397446/b33e9774-097e-4627-8f69-ede7ff38a1d8)

**Comment by Marc-Antoine-B** [comment]
Voici comme Radzen gère les PanelMenuItem :

Path="/" pour aller sur une page souligue en effet le bouton mais pas le Click="fonction"

Jw l'ai géré grâce à la sessionStorage donc c'est une fonction qui va sur le groupe. Pour si peu ça restera comme ça.
