### ISSUE TITLE
Aligner les boutons "CRÉER" et "ANNULER"

### ISSUE THREAD

**Issue by DarOli2131947** [ChuckD46/STIMULUS_V2#133]
Les boutons ne sont pas alignés : 

![image](https://github.com/ChuckD46/STIMULUS_V2/assets/89397446/9f2fab91-207d-43b1-bc03-e5c0a8110343)

(Ils devrait être un peut plus sur la gauche pour s'aligner avec le forms au-dessus)

**Comment by Marc-Antoine-B** [comment]
Sera réglé avec ce que Charles fait.
