### ISSUE TITLE
UI for adding new Noeud should be in front

### ISSUE THREAD

**Issue by DarOli2131947** [ChuckD46/STIMULUS_V2#135]
When creating a new Noeud in a Graphe, it's possible for an already existing Noeud to show on top of the form fields for creating the new Noeud : 
![image](https://github.com/ChuckD46/STIMULUS_V2/assets/89397446/a3616377-04f1-4686-b03b-e373069ee5db)

**Comment by corentinurlacher** [comment]
Complexe a patch, car c'est le rendu fait par le navigateur. Il faudrait que je vois pour modifier l'ordre de rendu mais ca risque de prendre beaucoup de temps.
