### ISSUE TITLE
Noeud buttons slight offset when setting "Rayon" to something greater than 40

### ISSUE THREAD

**Issue by DarOli2131947** [ChuckD46/STIMULUS_V2#146]
When setting the "Rayon" of a Noeud to something above 40, the buttons that surround the Noeud get offset in weird ways : 

(Rayon 41 on the left, Rayon 80 on the right)
![image](https://github.com/ChuckD46/STIMULUS_V2/assets/89397446/1a6d3478-e119-47f4-bef4-0f8d7c708ebe)

(Rayon 40 for reference)
![image](https://github.com/ChuckD46/STIMULUS_V2/assets/89397446/b35e7b78-4bd4-47a6-b19e-5d4e46ec7ffd)

_Small note, this was fixed in an earlier version but now it's back??_

**Comment by corentinurlacher** [comment]
Note : probleme avec les valeurs impairs
