### ISSUE TITLE
Noeuds that have the same name share their pages

### ISSUE THREAD

**Issue by DarOli2131947** [ChuckD46/STIMULUS_V2#151]
In the video, there are 2 Noeuds, each of them have the same name but they're technically different Noeuds. When one is modified, the other is affected as well : 

https://github.com/ChuckD46/STIMULUS_V2/assets/89397446/8175a284-782c-454c-9e50-3a96d0ca9e8f

This is what both Noeuds look like in the database : 
![image](https://github.com/ChuckD46/STIMULUS_V2/assets/89397446/c154af36-2c3a-4ee5-95ef-f7ebd5d90c5c)
![image](https://github.com/ChuckD46/STIMULUS_V2/assets/89397446/8b9711b3-07c1-4ca3-bee2-aa89b2d02be7)

**Comment by Marc-Antoine-B** [comment]
hmmm pas supposé vu que ça prend le NoeudId et qu'il est différent. Je vais regarder ça, je prend en charge l'issue merci du retour fallais le trouvé
